#!/bin/bash

HOST=127.0.0.1
PORT=8500

while getopts h:p: OPT; do
    case $OPT in
        h)
            HOST=$OPTARG;;
        p)
            PORT=$OPTARG;;
    esac
done

curl -s http://$HOST:$PORT/v1/status/leader | fgrep -q '""'

STATUS=$?

if [[ $STATUS == "0" ]]; then
    exit 2
elif [[ $STATUS == "1" ]]; then
    exit 0
fi
